### ISSUE TITLE
Question about client-initiated renegotiations

### ISSUE THREAD

**Issue by bsharper** [cesanta/ssl_wrapper#6]
Is there a way to disable client-initiated renegotiations in ssl_wrapper? I've tried compiling against OpenSSL 1.0.2d with these additional flags added to SSL_CTX_set_options:

SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION
SSL_OP_CIPHER_SERVER_PREFERENCE

I'm manually testing if this is available by running the following command:
`openssl s_client -connect localhost:443`
Then after the connection enter:
`HEAD / HTTP/1.0`
`R`

After which the text "RENEGOTIATING" appears.

From what I've read, the main issue with client-initiated renegotiations is that it potentially allows DOS attacks but I'd prefer to disable it altogether if possible.

**Comment by cpq** [comment]
Thanks for the analysis @bsharper 
No, there is no way to disable renegotiations from the API. Actually, existing API doesn't allow to tweak SSL params. So the only way is to hack the source and do it manually as you did.
Interesting that `SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION` did not do that for you - perhaps because it only affects server-initiated renegotiations?
There are few other relevant flags mentioned in the docs, like `SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION`, I'd try them too.
